version: 2

references:
  ## Cache
  cache_key: &cache_key
    key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "player/build.gradle" }}-{{ checksum "sample/build.gradle" }}
  restore_cache: &restore_cache
    restore_cache:
      <<: *cache_key
  save_cache: &save_cache
    save_cache:
      <<: *cache_key
      paths:
        - ~/.gradle

  ## Docker image configurations
  android_config: &android_config
    working_directory: ~/workspace
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx4G

jobs:
  ## Run player unit tests
  player_test_unit:
    <<: *android_config
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - *save_cache
      - run:
          name: Run player unit tests
          command: ./gradlew -PciBuild=true :player:testReleaseUnitTest
      - store_artifacts:
          path: player/build/reports/
          destination: /reports/
      - store_test_results:
          path: player/build/test-results/
          destination: /test-results/

workflows:
  version: 2
  workflow:
    jobs:
      - player_test_unit